# Simple workflow for deploying static content to GitHub Pages
name: Generate Dokka docs and push to gh-pages branch
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Build and generate Dokka docs
        run: ./gradlew dokkaHtml

      - name: Verify Dokka HTML docs were generated
        run: |
          if [ -z "$(ls -A build/dokka/html)" ]; then
            echo "Error: Dokka HTML output directory is empty!"
            exit 1
          fi

      
      - name: Deploy Dokka HTML docs to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/dokka/html # make sure everything is commited at the root
          keep_files: false
