name: Publish Kotlin Library

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (overrides release tag)'
        required: false
        default: ''
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Determine version to use
        id: set_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ -z "${{ github.event.inputs.version }}" ]]; then
              echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            else
              echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            fi
          else
            echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi

      - name: Build and generate Dokka docs
        run: ./gradlew clean build dokkaHtml dokkaJavadoc -PreleaseVersion=$RELEASE_VERSION

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_SIGNING_PASSWORD }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache -PreleaseVersion=$RELEASE_VERSION --no-daemon

      - name: Deploy Dokka HTML docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/dokka
          keep_files: false
